/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedScanRouteImport } from './routes/_authenticated/scan'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedQuestsRouteImport } from './routes/_authenticated/quests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMapRouteImport } from './routes/_authenticated/map'
import { Route as AuthenticatedJourneyRouteImport } from './routes/_authenticated/journey'
import { Route as AuthenticatedJournalRouteImport } from './routes/_authenticated/journal'
import { Route as AuthenticatedBadgesRouteImport } from './routes/_authenticated/badges'
import { Route as AuthenticatedAchievementsRouteImport } from './routes/_authenticated/achievements'
import { Route as AuthenticatedArtifactIdRouteImport } from './routes/_authenticated/artifact.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScanRoute = AuthenticatedScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestsRoute = AuthenticatedQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapRoute = AuthenticatedMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJourneyRoute = AuthenticatedJourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJournalRoute = AuthenticatedJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBadgesRoute = AuthenticatedBadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAchievementsRoute =
  AuthenticatedAchievementsRouteImport.update({
    id: '/achievements',
    path: '/achievements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedArtifactIdRoute = AuthenticatedArtifactIdRouteImport.update({
  id: '/artifact/$id',
  path: '/artifact/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/artifact/$id': typeof AuthenticatedArtifactIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/achievements': typeof AuthenticatedAchievementsRoute
  '/badges': typeof AuthenticatedBadgesRoute
  '/journal': typeof AuthenticatedJournalRoute
  '/journey': typeof AuthenticatedJourneyRoute
  '/map': typeof AuthenticatedMapRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/scan': typeof AuthenticatedScanRoute
  '/artifact/$id': typeof AuthenticatedArtifactIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/achievements': typeof AuthenticatedAchievementsRoute
  '/_authenticated/badges': typeof AuthenticatedBadgesRoute
  '/_authenticated/journal': typeof AuthenticatedJournalRoute
  '/_authenticated/journey': typeof AuthenticatedJourneyRoute
  '/_authenticated/map': typeof AuthenticatedMapRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quests': typeof AuthenticatedQuestsRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/scan': typeof AuthenticatedScanRoute
  '/_authenticated/artifact/$id': typeof AuthenticatedArtifactIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/achievements'
    | '/badges'
    | '/journal'
    | '/journey'
    | '/map'
    | '/profile'
    | '/quests'
    | '/rewards'
    | '/scan'
    | '/artifact/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/achievements'
    | '/badges'
    | '/journal'
    | '/journey'
    | '/map'
    | '/profile'
    | '/quests'
    | '/rewards'
    | '/scan'
    | '/artifact/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/achievements'
    | '/_authenticated/badges'
    | '/_authenticated/journal'
    | '/_authenticated/journey'
    | '/_authenticated/map'
    | '/_authenticated/profile'
    | '/_authenticated/quests'
    | '/_authenticated/rewards'
    | '/_authenticated/scan'
    | '/_authenticated/artifact/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scan': {
      id: '/_authenticated/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AuthenticatedScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quests': {
      id: '/_authenticated/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedQuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/map': {
      id: '/_authenticated/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AuthenticatedMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journey': {
      id: '/_authenticated/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof AuthenticatedJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/journal': {
      id: '/_authenticated/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AuthenticatedJournalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/badges': {
      id: '/_authenticated/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof AuthenticatedBadgesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/achievements': {
      id: '/_authenticated/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AuthenticatedAchievementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/artifact/$id': {
      id: '/_authenticated/artifact/$id'
      path: '/artifact/$id'
      fullPath: '/artifact/$id'
      preLoaderRoute: typeof AuthenticatedArtifactIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAchievementsRoute: typeof AuthenticatedAchievementsRoute
  AuthenticatedBadgesRoute: typeof AuthenticatedBadgesRoute
  AuthenticatedJournalRoute: typeof AuthenticatedJournalRoute
  AuthenticatedJourneyRoute: typeof AuthenticatedJourneyRoute
  AuthenticatedMapRoute: typeof AuthenticatedMapRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestsRoute: typeof AuthenticatedQuestsRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedScanRoute: typeof AuthenticatedScanRoute
  AuthenticatedArtifactIdRoute: typeof AuthenticatedArtifactIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAchievementsRoute: AuthenticatedAchievementsRoute,
  AuthenticatedBadgesRoute: AuthenticatedBadgesRoute,
  AuthenticatedJournalRoute: AuthenticatedJournalRoute,
  AuthenticatedJourneyRoute: AuthenticatedJourneyRoute,
  AuthenticatedMapRoute: AuthenticatedMapRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestsRoute: AuthenticatedQuestsRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedScanRoute: AuthenticatedScanRoute,
  AuthenticatedArtifactIdRoute: AuthenticatedArtifactIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
